version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: docker-compose run wasmVideoTranscoderService

workflows:
  build-and-test:
    jobs:
      - build-and-test
