version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: sudo apt-get purge --auto-remove nodejs
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: sudo apt install nodejs
      - run: sudo apt install build-essential
      - run: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
