version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      - run: source ~/.profile
      - run: nvm install 14
      - run: nvm use 14
      - run: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
