version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
